title: Flexbox Patterns

description: 使用CSS flexbox构建超棒的UI 这里包含里一些实例和源代码
baseurl: ""
url: ""
permalink: pretty

# Build settings
markdown: kramdown

sass:
    style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - assets/examples
  - assets/styles
